// user-client/web/src/App.vue
<script setup lang="ts">
// 国际化
import zhCN from 'ant-design-vue/es/locale/zh_CN';
import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn';
dayjs.locale('zh-cn');

</script>

<template>
  <div class="root-app">
    <a-config-provider :locale="zhCN">
      <router-view></router-view>
    </a-config-provider>
  </div>
</template>

<style scoped>

</style>

// user-client/r-web/src/App.tsx
import './App.scss'
import {BrowserRouter} from "react-router";
import useRoutes from "./routes";
import { ConfigProvider } from 'antd';
import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn';
import zhCN from 'antd/locale/zh_CN';

dayjs.locale('zh-cn');

function App() {
  return (
    <ConfigProvider locale={zhCN} theme={{cssVar: true}}>
      <BrowserRouter>
        {useRoutes()}
      </BrowserRouter>
    </ConfigProvider>
  )
}

export default App
